### ISSUE TITLE
Saga TrackingToken Default

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#181]
As a follow up of [#1019](https://github.com/AxonFramework/AxonFramework/issues/1019), the [Saga Infrastructure](https://docs.axoniq.io/reference-guide/axon-framework/sagas/infrastructure) section could use a short notice that a Saga `TrackingEventProcessor` will by default have its token start at the head of the stream.

**Comment by SaraTorrey** [comment]
Put this text under EP - Saga
