### ISSUE TITLE
End Saga on Deadline Handler

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#182]
As follow up on [#1469](https://github.com/AxonFramework/AxonFramework/issues/1469), the [Deadline](https://docs.axoniq.io/reference-guide/axon-framework/deadlines/deadline-managers#handling-a-deadline) page should receive a notice that a saga can end it's lifecycle on a deadline handler by using the `@EndSaga` annotation.

**Comment by SaraTorrey** [comment]
req's a note

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
