### ISSUE TITLE
Serialized type info during Upcasting process

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#184]
Issue [#1560](https://github.com/AxonFramework/AxonFramework/issues/1560) introduced the functionality to retrieve the serializer used for the message being upcasted. This info is valuable to know, as it allows the user to write a correct upcaster. Albeit short, the [Event Versioning](https://docs.axoniq.io/reference-guide/axon-framework/events/event-versioning) page should receive a notice which explains this option.

**Comment by SaraTorrey** [comment]
note is enough
If you have upcasters during a transition you want to make sure that your upcaster can handle both jackson and xtreme.

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
