### ISSUE TITLE
Automatic Revision based snapshot filtering

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#185]
Issue [#1588](https://github.com/AxonFramework/AxonFramework/issues/1588) introduced a dedicated `SnapshotFilter` implementation which checks for the `@Revision` annotation.
If present, the revision in the annotation is validated with the revision in the snapshot, which will be used to filter out non-matching snapshots from the `Repository`'s loading process.

The [Snapshotting](https://docs.axoniq.io/reference-guide/axon-framework/tuning/event-snapshots) page should receive a short description that when the `@Revision` annotation is used on the aggregate, that they can expect snapshots to be filtered out automatically.

**Comment by SaraTorrey** [comment]
The revision (annotation you can place on the class) has influence on the serialized format. Snapshot is also serialized. Payload revision (column also in AS) this is used for agg snapshots. The revision can be used for snapshot format. We (AF) automatically format these 

This needs to be section

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
