### ISSUE TITLE
ScopeDescriptor as resolved parameter on message handling functions

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#186]
The [Supported Parameters](https://docs.axoniq.io/reference-guide/axon-framework/messaging-concepts/supported-parameters-annotated-handlers) section should include the newly added `ScopeDescriptor` as a possibility to be resolved. A notice specifying that the `ScopeDescriptor` currently only shows something meaningful for Aggregates and Sagas (as those are the sole `ScopeDescriptor` implementations) should be defined too. This issue is based on [this](https://github.com/AxonFramework/AxonFramework/pull/1631) framework issue.

**Comment by SaraTorrey** [comment]
currently used by the deadline manager to know in what scope the DM has been used. scope is an id

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
