### ISSUE TITLE
Spring bean Handler Resolving change

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#187]
Issue [#1632](https://github.com/AxonFramework/AxonFramework/pull/1632) has seen a change in how Spring beans are resolved for message handling methods. Specifically that the `@Autowired` annotation should be used to get the revamped solution. This adjustment should be reflected on the [Supported Parameters for Annotated Handlers](https://docs.axoniq.io/reference-guide/axon-framework/messaging-concepts/supported-parameters-annotated-handlers) page.

**Comment by SaraTorrey** [comment]
change in the same page is req'd
dif is that recently a contributor made some changes how spring beans are resolved. 
If they want to wire a spring bean they should use @Autowired -

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
