### ISSUE TITLE
BeanValidationInterceptor changes

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#191]
The [Message Intercepting](https://docs.axoniq.io/reference-guide/axon-framework/messaging-concepts/message-intercepting#command-interceptors) page defines that structural message validation is done through the `BeanValidationInterceptor`. Although true, this version is only usable with `javax`. Users which are moving to a `jakarta` approach of bean validation should start using the `JakartaBeanValidationInterceptor`.
This shift (as introduced in [this](https://github.com/AxonFramework/AxonFramework/pull/1717) pull request) should be made clear on the Message Intercepting page.

**Comment by SaraTorrey** [comment]
BeanValidationInterceptor is used to validate beans - this is done through javax 
This is also present in the case of queries as well as the commands. (we think)

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #193.
