### ISSUE TITLE
Typo in Kafka Section

### ISSUE THREAD

**Issue by rhubarb** [AxonIQ/reference-guide#235]
In https://docs.axoniq.io/reference-guide/extensions/kafka#publishing-events-to-kafka

It reads "Tracking Event Processor - publication of messages to Kafka is run in a different thread (and Unit of Work)
**then** the one which published the events to the event bus."
"then" should be "than"

**Comment by smcvb** [comment]
Thanks for pointing this out, @rhubarb!
Closing this issue as it has been resolved in commit e276e89
