### ISSUE TITLE
Incorrect documentation for serverside access control properties

### ISSUE THREAD

**Issue by mlindhout** [AxonIQ/reference-guide#240]
In [access-control-se.md](https://github.com/AxonIQ/reference-guide/blob/master/axon-server/security/access-control-se.md) the properties `axoniq.axonserver.token` and `axoniq.axonserver.adminToken` are incorrect. As per the code, token and adminToken are `@NestedConfigurationProperty`s, so the nested `accesscontrol` property must be added. The correct properties are:

- axoniq.axonserver.accesscontrol.token
- axoniq.axonserver.accesscontrol.adminToken

Steps to reproduce the bug. Follow the current documentation by starting an Axon SE instance with in server.properties:

```
axoniq.axonserver.accesscontrol.enabled=true
axoniq.axonserver.token=app-token
axoniq.axonserver.adminToken=admin-token
```

And execute the specified curl command:

```
curl -H 'AxonIQ-Access-Token: app-token' -s http://localhost:8024/v1/public/users | jq
```

Result: **Invalid Token**

**Comment by MGathier** [comment]
Thanks for bringing this to our attention. I have updated the information in the documentation.
