### ISSUE TITLE
annotationAttributes is deprecated but still used in examples

### ISSUE THREAD

**Issue by rhubarb** [AxonIQ/reference-guide#277]
The example code under Handler Enhancers uses code like this:

    return original.annotationAttributes(MyAnnotation.class) // 3

but firstly, that method is deprecated, and secondly, the method it recommends in the javadoc comment to use instead "attribute()" will not work for a completely custom annotation like this (as far as I can tell)

**Comment by smcvb** [comment]
Thanks for bringing this to our attention, @rhubarb.
You're right, the sample on the Handler Enhancers page isn't correct.
As off 4.5 of Axon Framework, to be exact.
We'll provide an update to fix this predicament.

**Comment by smcvb** [comment]
Closing this issue since it is resolved in commit 872273f0dfe09e17ad57e3dbd1071763d2968ead.
