### ISSUE TITLE
framework/command/infrastructure still uses AxonConfiguration 

### ISSUE THREAD

**Issue by jangalinski** [AxonIQ/reference-guide#297]
https://github.com/AxonIQ/reference-guide/blob/master/axon-framework/axon-framework-commands/infrastructure.md#simplecommandbus

With 4.6. this is deprecated and we have to use `SpringConfigurer.buildConfiguration()`.

**Comment by smcvb** [comment]
Turns out this old fashioned configuration approach is still present on several pages... Thanks for notifying us of this, @jangalinski. Working on it as we speak.

**Comment by smcvb** [comment]
Closing this issue, as it has been resolved in commit d58a5a790714dbb8042e1cf28003b3136e5ef042.
