### ISSUE TITLE
Improve page 'Supported Parameters for Annotated Handlers'

### ISSUE THREAD

**Issue by tbvh** [AxonIQ/reference-guide#329]
To improve the docs for the annotated handlers it would make sense to show the possible parameters in a table.

It makes it easier to scan for specific parameters and it can improve clarity about whether or not a parameter annotation is required.

Additionally the page should mention the `ReplayStatus` type parameter for event handlers.

**Comment by smcvb** [comment]
Thanks for the suggestion, @tbvh!
Perhaps you're up to do a pull request for this? That would be the best way to relay what your intention is.

**Comment by smcvb** [comment]
Closing this issue, as it's been resolvd in pull request #333.
