### ISSUE TITLE
Change Maven central search link and Maven/Gradle dependencies info

### ISSUE THREAD

**Issue by bert-laverman** [AxonIQ/reference-guide#33]
The introduction paragraph to "Getting started" states:

    ...or configure a repository for your build system ([Maven](https://mvnrepository.com/artifact/org.axonframework/axon), Gradle, etc).

1) The link on the name "Maven" should point to the Maven project page (http://maven.apache.org/), just as "Gradle" should get one pointing at https://gradle.org/. The current link shows no information on Maven, nor information on how to configure the dependency.

2) Rather than use a link to mvnrepository.com, I suggest we use https://search.maven.org/search?q=g:org.axonframework%20AND%20v:4.0.

3) Add something like "Click the link on the version number to get snippets fro your `pom.xml` or `build.gradle` file, or re-introduce the snippet on our page.

4) Since the re-organisation of the package structure, there is no longer a "safe starter" such as the axon-core module, which gives you all the classes you need for common situations. Add a section "Axon Framework modules" to provide information on which modules are needed for what.

**Comment by idugalic** [comment]
@smcvb yes, section II.B (`4.0-restructuring/setting-up/maven-dependencies`) should describe this. It is a draft version at the moment:

"Axon Framework modules" is divided to "Main/Core modules `org.axonframework`" and "Extension modules `org.axonframework.extensions`" This can be clickable, **pointing to** https://search.maven.org as @bert-laverman suggested. It is a good idea to list all modules within specific group, and to be able to copy/paste maven coordinates for the desirable version

Additionally, we can introduce a module list on the page itself (within the guide, and not referring to maven central), which could be tricky to maintain in the future

**Comment by smcvb** [comment]
Closing as issue has been resolved.
