### ISSUE TITLE
Deprecated method in DbSchedulerDeadlineManager bean definition

### ISSUE THREAD

**Issue by nils-christian** [AxonIQ/reference-guide#334]
Hi,

Just a minor issue. The bean definition of the _DbSchedulerDeadlineManager_ uses the deprecated _spanFactory_ builder method.

I provide a PR for this.

Best regards

  Nils

**Comment by smcvb** [comment]
Thanks so much for taking the effort to draft an issue *and* PR for this, @nils-christian!
I've approved the changes you made and merged them into the RefGuide.

Hence, I am closing this issue since it is resolved by pull request #335.
