### ISSUE TITLE
Decribe Section 3.C: Query Handling

### ISSUE THREAD

**Issue by bert-laverman** [AxonIQ/reference-guide#36]
Provide a description for handling and dispatching `QueryMessages` in an Axon application. In doing so, describe point-to-point, scatter-gather and subscription queries.

**Comment by smcvb** [comment]
Revamped the Query Handling pages for the chapters "Implementing Domain Logic" and "Configuring Infrastructure Components". Deemed sufficient for now, so closing this issue.
