### ISSUE TITLE
Restructuring 4.0 - Introduction/quick-start

### ISSUE THREAD

**Issue by idugalic** [AxonIQ/reference-guide#42]
Communicate the presence of the Download page.

1. Get everything you need by downloading [QuickStart archive](https://axoniq.io/download)

 2. Unzip `AxonQuickStart-VERSION.zip`

 3. Run the Axon Server: `$ java -jar AxonServer/axonserver-VERSION.jar`

 4. Axon Server web dashboard should be available here `http://localhost:8024/`

 5. Run the demo application: `$ cd giftcard-demo && ./mvnw spring-boot:run`

 6. Demo application should be available here `http://localhost:8080/`

 7. Explore the `README.md`

**Comment by smcvb** [comment]
Closing as issue has been resolved.
