### ISSUE TITLE
Restructuring 4.0 -Introduction/architecture-overview

### ISSUE THREAD

**Issue by idugalic** [AxonIQ/reference-guide#43]
We have a main page `introduction/architecture-overview/architecture-overview.md`. Focus on message-driven approach: commands, queries, events, location transparency. CQRS as a pattern. Replace the arch image we have now with the latest one.

and two sub pages:
 - `introduction/architecture-overview/ddd-cqrs-patters.md` (How CQRS fits in DDD patterns and concepts)
 - `introduction/architecture-overview/event-driven-microservices.md` (High view architecture style. Bounded Context = Microservice, Aggregate = Microservice. Saga as orchestrator or choreographer)

**Comment by smcvb** [comment]
Closing issue as it has been resolved.
