### ISSUE TITLE
Include hint for JdbcSagaStore that Schema ist not automatically created

### ISSUE THREAD

**Issue by hatzlj** [AxonIQ/reference-guide#49]
Currently nor the documentation under https://docs.axoniq.io/reference-guide/1.2-domain-logic/sagas#saga-repository-and-saga-store neither the Javadoc of JdbcSagaStore does state, that the database schema is not initialized automatically. 
It would be helpfult to give a hint that you actually need to do this for the JdbcSagaStore to work somewhere.

**Comment by smcvb** [comment]
Thanks for pointing this out @hatzlj, I'll ensure we'll take this into account in the configuration section.

**Comment by smcvb** [comment]
Closing this issue, since commit 32b176db48bcc80218949458d0c9eb4fd9180eab resolve it.
