### ISSUE TITLE
Restructuring 4.0 - configuring-infrastructure-components/event-processing

### ISSUE THREAD

**Issue by idugalic** [AxonIQ/reference-guide#50]

**Comment by fransvanbuul** [comment]
I got a specific question from a customer, referencing my blog on read model performance, on how to set batch size. That's currently missing from the manual. I helped them by sharing the following code (Spring-based):

```
@Autowired
public void configure(EventProcessingConfigurer configurer) {
    configurer.registerTrackingEventProcessor(
            "ArrivedShipment",
            Configuration::eventStore,
            c -> TrackingEventProcessorConfiguration.forSingleThreadedProcessing().andBatchSize(100)
    );
}
```

I think something like that should be added to the manual.

**Comment by smcvb** [comment]
Closing as issue has been resolved.
