### ISSUE TITLE
Major Reference Guide Restructuring/Refactoring [4.0]

### ISSUE THREAD

**Issue by marleinevankampen** [AxonIQ/reference-guide#6]
Rewrite the chapters of the Axon Framework in the reference guide to reflect the logic in Axon 4.0.

The current version can be found on docs.axoniq.io. AxonIQ/reference-guide is the code base for the new reference guide. 

As placing comments in the reference guide is not possible - hereby a list of ideas for changes
- [Axon Framework Background](https://docs.axoniq.io/reference-guide/axon-framework/introduction#axon-framework-background) -> Remove Terracotta / Gigaspaces reference
- [Getting Started](https://docs.axoniq.io/reference-guide/axon-framework/introduction#getting-started) -> Is there a Gradle repository where we can link to?
- [Configure Maven](https://docs.axoniq.io/reference-guide/axon-framework/introduction#configure-maven) -> Mention the Spring Boot starter?
- [Architecture Overview](https://docs.axoniq.io/reference-guide/1.1-concepts/architecture-overview#axon-module-structure) -> Is the SLF4J versioning still correct?
- [Modules](https://docs.axoniq.io/reference-guide/1.1-concepts/architecture-overview#main-modules) -> Is the setup of the modules still correct for 4.0?
- [Modules](https://docs.axoniq.io/reference-guide/1.1-concepts/architecture-overview#main-modules) -> `axon-spring` mention something about the starter here, or at least a reference to the Spring Boot starter example
- [Commands](https://docs.axoniq.io/reference-guide/1.1-concepts/messaging-concepts#commands) -> Explain "wrapped using one of the CommandMessage implementations" a bit more.
- [Event handling](https://docs.axoniq.io/reference-guide/1.2-domain-logic/event-handling) -> Rewrite to use the `EventProcessingConfiguration` instead of the `EventHandlingConfiguration`
- [Saga](https://docs.axoniq.io/reference-guide/~/drafts/-LP6I1bv6Y1BRybVz5IS/primary/1.2-domain-logic/sagas#saga) -> Update with possibility to have multiple sagas in one event processor?
- [Saga](https://docs.axoniq.io/reference-guide/~/edit/drafts/-LP6I1bv6Y1BRybVz5IS/1.2-domain-logic/sagas#managing-associations) -> Quartz 2 still relevant?
- [1.1.3 Configuration API](https://docs.axoniq.io/reference-guide/1.1-concepts/configuration-api) and [1.3.5] Spring Boot Auto Configuration](https://docs.axoniq.io/reference-guide/1.3-infrastructure-components/spring-boot-autoconfiguration) should link to each other or at least be in the same chapter. 
- [Event processing](https://docs.axoniq.io/reference-guide/1.3-infrastructure-components/event-processing) - Add information about replaying events

**Comment by smcvb** [comment]
Closing epic as restructuring has been resolved.
