### ISSUE TITLE
Configuring Kafka as a Message Source

### ISSUE THREAD

**Issue by pms-github** [AxonIQ/reference-guide#64]
The current Reference Guide does no provide documentation on how to configure Kafka as a (Event) Message Source in an Axon application.
It would be beneficial if this is introduced. As this is about one of the Axon Framework extensions, it will be added in the appendix section.

Note that the Kafka extension is a release candidate - hence the contents of the guide and the code are subject to change.

- Original Message
Axon4 Kafka integration documentation - inadequet.
Would appreciate, if configuration related details are added along with sample example.

**Comment by pms-github** [comment]
Expected release date for final release date for Axon4 Kafka extension and documentation ?

**Comment by smcvb** [comment]
We are mostly focusing on Axon Framework and Axon Server at the moment. Hence I am not at the point I can give you a date on a full release of the Kafka extension at the moment.

This issue will be updated accordingly once  we'll start working on it.

**Comment by pms-github** [comment]
Cheers ! would be following it till that point :)

**Comment by michaelwijaya96** [comment]
is that point coming out yet?

**Comment by smcvb** [comment]
Expect movement in the Axon Kafka Extension soon now; Axon release 4.2 was more pressing and thus held back further development around the kafka extension. Regardless, if you want to see movement in this extension you can obviously also contribute to the project as well; it is open source after all. Any help is much appreciated!

**Comment by michaelwijaya96** [comment]
@smcvb okay, looking forward for the next version of axon kafka extension! Thanks

**Comment by smcvb** [comment]
@simone that would ensure that *all* your `TrackingEventProcessor`s in an Axon application would use the `KafkaMessageSource`.

If that's what you want, then yes that's the missing part.
However, I'd say it highly depends on what said application does and the majority of users will want to be very specific about which Tracking Event Processor instances receives which `StreamableMessageSource`.

**Comment by smcvb** [comment]
Pull request #106 will resolve the issue of the Kafka documentation being inadequate.
We waited with this resolution until we made all the major changes to the Kafka Extension we wanted. Thus to ensure no duplicate work was done in the Reference Guide.

As the exact request of this issue is being addressed in #106, I will be closing this ticker as resolved.
