### ISSUE TITLE
Unclear section titles about deadlines

### ISSUE THREAD

**Issue by sgrimm-sg** [AxonIQ/reference-guide#75]
The "Deadline handling" subsection under "Complex Business Transactions" doesn't mention `@DeadlineHandler` and gives no indication that there's a completely separate deadline handling API in addition to the event scheduler.

**Comment by smcvb** [comment]
Good point @sgrimm-sg. I will make a quick reference solution in the `Deadline Handling` section to clarify this. 
We still have plans to make a more consolidated solution regarding documentation of Deadlines.
A more thorough solution will thus be introduced at a later stage.

**Comment by smcvb** [comment]
Closing as issue has been resolved in commit d403149.
