### ISSUE TITLE
Use a spell checker

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonIQ/reference-guide#79]
You have a bunch of typos in the docs.
e.g.

> Axon finds its use in both large monolithic applications, wherein the internal structure ...

> It is unlikely that all technology stacks used follow the same messaging ...

**Comment by abuijze** [comment]
I'm pretty sure there are "a bunch of typos" in the docs. However, the two sentences you use as an example, don't contain any.
We value your attempt to contribute to the project. Would appreciate if you'd do that either through constructive criticism or, even better, pull requests.

**Comment by Sam-Kruglov** [comment]
Well, that was embarrassing :)
Sorry, in the first sentence, I didn't know the word "wherein" existed and in the second, I was confused with the placement of "used" and "follow" together. Anyway, there is a PR for introduction spelling, I took a bit of time to go through it
