### ISSUE TITLE
Template render error while generating gitbook locally

### ISSUE THREAD

**Issue by prayadav** [AxonIQ/reference-guide#85]
gitbook-cli build is failing while generating pages for handling-events.md with _unknown block tag:tabs_ error

`
error: error while generating page "implementing-domain-logic/event-handling/handling-events.md":
Template render error: ./AxonReferenceGuide/reference-guide/implementing-domain-logic/event-handling/handling-events.md) [Line 61, Column 2]
  unknown block tag: tabs
`

**Comment by idugalic** [comment]
@prayadav New version (ver 2) of the GitBook platform does not support static site generator model any more: [https://docs.gitbook.com/v2-changes/important-differences#cli-toolchain](https://docs.gitbook.com/v2-changes/important-differences#cli-toolchain)

This admittedly has some drawbacks. The main one being that you can no longer host a GitBook generated documentation yourself.

**Comment by smcvb** [comment]
Due to @idugalic comment, there is currently not a way we can tailor towards locally building the Reference Guide. Thanks for marking the comment @prayadav, I'll ensure the README of this repository is specific about this as well. For now, I will be closing this issue.

**Comment by smcvb** [comment]
By the way, I've updated the main `README.md` to specify this situation, and dropped the `README-local.md` which specified how to build the guide yourself entirely.
