### ISSUE TITLE
Update link to 'Event Sourced' Aggregates on aggregate.md

### ISSUE THREAD

**Issue by anno1985** [AxonIQ/reference-guide#87]
"...Axon will configure your Aggregate as an 'Event Sourced' Aggregate (as described here)" points to `../../introduction/architecture-overview/event-driven-microservices.md` but should probably go to `../../introduction/architecture-overview/architecture-overview.md#event-sourcing`.

**Comment by smcvb** [comment]
Thanks for the suggestion @anno1985, I've adjusted it as of Ref.Guide 4.0 in commit bf23563.

**Comment by anno1985** [comment]
@smcvb are you guys generally accepting PRs for the docs? If so, I could fix a few grammar and link issues like this one while I read through them, provided you tell me how granular you want those PRs to be... :)

**Comment by smcvb** [comment]
We would very much welcome feedback, improvements and/or typo fixes as pull requests @anno1985!
If you have the time to provide some, that would be great.

I'd argue that it's easiest to have a PR per typo-corrected file.
Granted, we'll need be overly bothered you have several files for typos in the PR.
