### ISSUE TITLE
Document how to configure aggregate caching

### ISSUE THREAD

**Issue by sgrimm-sg** [AxonIQ/reference-guide#89]
The "Optimizing Aggregate loading" page has a section on caching describing some of the constraints and considerations to be aware of when using caching, but it doesn't say how to actually enable or configure caching. A configuration example like the one for snapshotting would be helpful.

**Comment by smcvb** [comment]
Good suggestion @sgrimm-sg, I'll ensure we put this on the backlog.

**Comment by smcvb** [comment]
Commit 25e0bf9e3fea46ac5f5d4e70664c0e265d0db62f solves this issue. Hence, I'll close this ticket as resolved.
