### ISSUE TITLE
Document processing groups

### ISSUE THREAD

**Issue by sgrimm-sg** [AxonIQ/reference-guide#91]
The documentation refers to processing groups in a couple places, but never says what they are, how they're assigned by default, or why you'd want to customize them.

**Comment by smcvb** [comment]
Good point @sgrimm-sg, we'll look into adding a more specific section/paragraph on the delegating between Event Handlers, Processing Groups and Event Processors.

**Comment by smcvb** [comment]
This adjustment is dealt with in pull request #210. 
As such, I feel confident this issue is resolved.
Feel free to provide the following suggestions if some of the contents are still missing, @sgrimm-sg.
