### ISSUE TITLE
Describe option of Micrometer metrics

### ISSUE THREAD

**Issue by smcvb** [AxonIQ/reference-guide#94]
The Monitoring and Metrics section currently only describe the option to use Dropwizard Metrics.
However, as of release 4.1, the framework also supports using Micrometer Metrics.

Both options should be described correctly in the `monitoring-and-metrics.md` page.
Additionally, the `axon-micrometer-metrics` module should be specified on the `maven-dependencies.md` page too.

**Comment by idugalic** [comment]
Done ! 
https://github.com/AxonIQ/reference-guide/commit/d03908406b3a87fcd05be173d8e16997809595bb
