### ISSUE TITLE
RDBMS Tuning appendix: class referred in "orm.xml" file has wrong package name

### ISSUE THREAD

**Issue by patrickhancke** [AxonIQ/reference-guide#96]
The https://docs.axoniq.io/reference-guide/appendices/rdbms-tuning#auto-increments-and-sequences paragraph advises to create a META-INF/orm.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<entity-mappings version="1.0" xmlns="http://java.sun.com/xml/ns/persistence/orm">
    <mapped-superclass access="FIELD" metadata-complete="false" class="org.axonframework.eventsourcing.eventstore.AbstractSequencedDomainEventEntry">
        <attributes>
            <id name="globalIndex">
                <generated-value strategy="SEQUENCE" generator="myGenerator"/>
                <sequence-generator name="myGenerator" sequence-name="mySequence"/>
            </id>
        </attributes>
    </mapped-superclass>
</entity-mappings>
```
In my opinion, the fully qualified class name for _AbstractSequencedDomainEventEntry_ is wrong, shouldn't this be _org.axonframework.eventhandling.AbstractSequencedDomainEventEntry_ ?

**Comment by smcvb** [comment]
You are completely right @patrickhancke, we missed adjusting this page in the upgrade from Axon 3 to 4. I'll change this right away.

**Comment by patrickhancke** [comment]
Thanks, already corrected it in my project.
